import type { Stock } from '../types';

export const generateInitialStocks = (): Stock[] => {
  return [
    // --- Index ETFs ---
    {
      symbol: 'SPY',
      name: 'S&P 500 ETF',
      price: 524.61,
      change: 1.23,
      changePercent: 0.23,
      sector: 'Index ETF',
      type: 'etf',
      description: 'Tracks the S&P 500 — the 500 largest US companies. Great for beginners who want broad market exposure.',
      volatility: 0.010,
    },
    {
      symbol: 'QQQ',
      name: 'Nasdaq 100 ETF',
      price: 444.72,
      change: 2.11,
      changePercent: 0.48,
      sector: 'Index ETF',
      type: 'etf',
      description: 'Tracks the top 100 Nasdaq companies, heavily weighted toward tech giants.',
      volatility: 0.015,
    },
    {
      symbol: 'DIA',
      name: 'Dow Jones ETF',
      price: 392.45,
      change: 0.87,
      changePercent: 0.22,
      sector: 'Index ETF',
      type: 'etf',
      description: 'Tracks the Dow Jones Industrial Average — 30 large blue-chip US companies.',
      volatility: 0.009,
    },
    // --- Individual Stocks ---
    {
      symbol: 'AAPL',
      name: 'Apple Inc.',
      price: 198.42,
      change: 1.64,
      changePercent: 0.83,
      sector: 'Technology',
      type: 'stock',
      description: 'Consumer technology company known for iPhone, Mac, and ecosystem services.',
      volatility: 0.018,
    },
    {
      symbol: 'MSFT',
      name: 'Microsoft Corporation',
      price: 415.32,
      change: 2.10,
      changePercent: 0.51,
      sector: 'Technology',
      type: 'stock',
      description: 'Software and cloud giant behind Windows, Office, Azure, and LinkedIn.',
      volatility: 0.016,
    },
    {
      symbol: 'NVDA',
      name: 'NVIDIA Corporation',
      price: 875.40,
      change: 12.30,
      changePercent: 1.43,
      sector: 'Technology',
      type: 'stock',
      description: 'Leading GPU manufacturer powering AI, gaming, and data center workloads.',
      volatility: 0.035,
    },
    {
      symbol: 'GOOGL',
      name: 'Alphabet Inc.',
      price: 165.81,
      change: -1.12,
      changePercent: -0.67,
      sector: 'Communication Services',
      type: 'stock',
      description: 'Internet services company with search, ads, cloud, and AI-focused products.',
      volatility: 0.021,
    },
    {
      symbol: 'AMZN',
      name: 'Amazon.com, Inc.',
      price: 184.73,
      change: 2.61,
      changePercent: 1.43,
      sector: 'Consumer Discretionary',
      type: 'stock',
      description: 'E-commerce and cloud computing company with global consumer and enterprise platforms.',
      volatility: 0.024,
    },
    {
      symbol: 'META',
      name: 'Meta Platforms, Inc.',
      price: 512.45,
      change: 3.20,
      changePercent: 0.63,
      sector: 'Communication Services',
      type: 'stock',
      description: 'Social media company behind Facebook, Instagram, WhatsApp, and the metaverse push.',
      volatility: 0.026,
    },
    {
      symbol: 'TSLA',
      name: 'Tesla, Inc.',
      price: 177.90,
      change: -4.20,
      changePercent: -2.31,
      sector: 'Consumer Discretionary',
      type: 'stock',
      description: 'Electric vehicle and clean energy company known for high volatility and innovation.',
      volatility: 0.042,
    },
    {
      symbol: 'JPM',
      name: 'JPMorgan Chase & Co.',
      price: 210.58,
      change: 1.33,
      changePercent: 0.64,
      sector: 'Financials',
      type: 'stock',
      description: 'Global financial services firm with consumer banking and investment operations.',
      volatility: 0.017,
    },
    {
      symbol: 'JNJ',
      name: 'Johnson & Johnson',
      price: 153.22,
      change: 0.49,
      changePercent: 0.32,
      sector: 'Healthcare',
      type: 'stock',
      description: 'Diversified healthcare company across pharmaceuticals, medtech, and consumer health.',
      volatility: 0.014,
    },
    {
      symbol: 'XOM',
      name: 'Exxon Mobil Corporation',
      price: 116.37,
      change: -0.91,
      changePercent: -0.78,
      sector: 'Energy',
      type: 'stock',
      description: 'Integrated energy company with upstream, downstream, and chemical operations.',
      volatility: 0.023,
    },
  ];
};

export const updateStockPrices = (stocks: Stock[]): Stock[] => {
  return stocks.map(stock => {
    const randomChange = (Math.random() - 0.5) * 2 * stock.volatility * stock.price;
    const newPrice = Math.max(stock.price + randomChange, 1);
    const change = newPrice - stock.price;
    const changePercent = (change / stock.price) * 100;
    return {
      ...stock,
      price: Number(newPrice.toFixed(2)),
      change: Number(change.toFixed(2)),
      changePercent: Number(changePercent.toFixed(2)),
    };
  });
};
